### ISSUE TITLE
virtualenv 不要放进仓库

### ISSUE THREAD

**Issue by pandada8** [helloqiu/flaskTest#1]

**Comment by pandada8** [comment]
包括其他的.DS_Store 等等,配置好你的gitignore

**Comment by helloqiu** [comment]
ok，其实这是我懒﻿T_T

**Comment by pandada8** [comment]
https://github.com/karan/joe

懒就用工具

还有你试试看 pip freeze 一下?
一般的python 仓库都是一个 requirements.txt

**Comment by helloqiu** [comment]
ok，我会加油(我是鶸
